version: 2.1

jobs:
  run_tests:
    working_directory: ~/repo
    docker:
      - image: golang:1.20
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install dependencies
          command: |
            go get -v -t -d ./...
      - run:
          name: Set up environment
          command: |
            echo "DRIVER=your_driver" > .env
            echo "DATABASE_URL=your_database_url" >> .env
            echo "PORT=your_port" >> .env
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: go test -v ./...

workflows:
  build_test:
    jobs:
      - run_tests
